{% set name = "jaraco.itertools" %}
{% set version = "6.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jaraco_itertools-{{ version }}.tar.gz
  sha256: 06c8727afcad659e29ce78773870428500f4daf6f13b9c2f5154ddb21cbca90d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools_scm >=3.4.1
  run:
    - python >={{ python_min }}
    - more-itertools >=4.0.0
    - inflect

test:
  requires:
    - python {{ python_min }}
  imports:
    - jaraco.itertools

about:
  home: https://github.com/jaraco/jaraco.itertools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional itertools in the spirit of stdlib's itertools.
  doc_url: https://github.com/jaraco/jaraco.itertools
  dev_url: https://github.com/jaraco/jaraco.itertools

extra:
  recipe-maintainers:
    - nehaljwani
