{% set name = "jaraco.itertools" %}
{% set version = "6.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6098edb37c6b8023f3794d42588a13bf75b2ca02b40ff9795c846bcbe0c1b46c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm >=1.15.0
  run:
    - python >={{ python_min }}
    - more-itertools >=4.0.0
    - inflect

test:
  requires:
    - python {{ python_min }}
  imports:
    - jaraco.itertools

about:
  home: https://github.com/jaraco/jaraco.itertools
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional itertools in the spirit of stdlib's itertools.
  doc_url: https://github.com/jaraco/jaraco.itertools
  dev_url: https://github.com/jaraco/jaraco.itertools

extra:
  recipe-maintainers:
    - nehaljwani
